services:
  send-catcher:
    build: 
      context: .
      dockerfile: send-catcher.Dockerfile
    restart: unless-stopped
    volumes:
      - ./sessions:/app/sessions
      - ./configuration.json:/app/configuration.json:ro
      - ./logs:/app/logs
    user: "1000:1000"